services:
  db_1:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
    - 5432:5432
    volumes:
       - ./data:/var/lib/postgresql/data