services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
    - 5432:5432 
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    volumes:
       - ./data:/var/lib/postgresql/data